compiler: ghc-8.2.1
resolver: lts-11.9

packages: [.]

extra-deps:
- katip-0.5.4.0
- git: git@github.com:carlohamalainen/amazonka
  commit: 0be280ededb58cad71c82c0f241e1eb8d326fd07
  subdirs:
  - amazonka
  - core
  - amazonka-glacier
