compiler: ghc-8.2.1
resolver: nightly-2017-11-01

packages: [.]

extra-deps:
- katip-0.5.4.0
- git: git@github.com:carlohamalainen/amazonka
  commit: b5e4e0d1ac9577e74d1f4e6ad922edf30a5bcd3a
  subdirs:
  - amazonka
  - core
  - amazonka-glacier
