resolver: lts-9.1

packages:
- '.'
- location:
    git: git@github.com:carlohamalainen/amazonka
    commit: 65dacf6d76dd712bfc18e34e9df36b5492f22bfa
  subdirs:
  - amazonka
  - core
  - amazonka-glacier

extra-deps: []

flags: {}

extra-package-dbs: []
